"""Regenerate every icon the site serves, from one set of numbers.

    python tools/make-icons.py

Writes favicon.ico, favicon.svg and apple-touch-icon.png in the repo root.

The geometry is sv-icon-black.svg's: a 112-radius disc in a 256 box, filled
with a diagonal #151515 -> #333333 gradient, and "Sv" in Arial Bold at 135 and
112 on baselines of 178 and 180, the pair centred as a whole - which is what
text-anchor="middle" does with two runs.

Two files rather than one because a .ico cannot know what the browser's tab
strip looks like. On a dark strip the black disc sinks into the background and
leaves the letters floating; favicon.svg carries a prefers-color-scheme rule
and inverts instead. Browsers that do not take an SVG favicon fall back to the
.ico, which is the light-strip drawing.

Requires Pillow and fontTools, and Arial Bold - so, in practice, Windows.
"""
import os

from PIL import Image, ImageDraw, ImageFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = r"C:\Windows\Fonts\arialbd.ttf"

M = 1024                                  # master raster size
K = M / 256.0                             # the geometry is in a 256 box
TOP, BOTTOM = (0x15, 0x15, 0x15), (0x33, 0x33, 0x33)
SIZES = [16, 24, 32, 48, 64, 128, 256]


# --------------------------------------------------------------- the raster
def master():
    im = Image.new("RGBA", (M, M), (0, 0, 0, 0))

    # The gradient runs corner to corner, so the mixing parameter is
    # (x + y) over twice the width.
    grad = Image.new("RGB", (M, M))
    gp = grad.load()
    for y in range(M):
        for x in range(M):
            t = (x + y) / float(2 * (M - 1))
            gp[x, y] = tuple(int(TOP[i] + (BOTTOM[i] - TOP[i]) * t + 0.5) for i in range(3))

    # The disc is drawn at 4x and downsampled: it is the only edge in the
    # whole mark, and the resampler makes a better one than ImageDraw.
    n = M * 4
    mask = Image.new("L", (n, n), 0)
    r, c = 112 * K * 4, 128 * K * 4
    ImageDraw.Draw(mask).ellipse([c - r, c - r, c + r, c + r], fill=255)
    im.paste(grad, (0, 0), mask.resize((M, M), Image.LANCZOS))

    big = ImageFont.truetype(FONT, int(135 * K))
    small = ImageFont.truetype(FONT, int(112 * K))
    ws, wv = big.getlength("S"), small.getlength("v")
    x = 128 * K - (ws + wv) / 2.0
    d = ImageDraw.Draw(im)
    d.text((x, 178 * K), "S", font=big, fill=(255, 255, 255, 255), anchor="ls")
    d.text((x + ws, 180 * K), "v", font=small, fill=(255, 255, 255, 255), anchor="ls")
    return im


src = master()
ico = os.path.join(ROOT, "favicon.ico")
src.resize((256, 256), Image.LANCZOS).save(ico, format="ICO",
                                           sizes=[(s, s) for s in SIZES])
print("favicon.ico       ", ", ".join(str(s) for s in SIZES))

# iOS squares the corners off against the wallpaper, so a transparent corner
# would show. Flatten onto white.
apple = Image.new("RGB", (180, 180), (255, 255, 255))
big = src.resize((180, 180), Image.LANCZOS)
apple.paste(big, (0, 0), big)
apple.save(os.path.join(ROOT, "apple-touch-icon.png"))
print("apple-touch-icon.png  180")


# ------------------------------------------------------------------ the SVG
font = TTFont(FONT)
upem = font["head"].unitsPerEm
glyphs = font.getGlyphSet()
cmap = font.getBestCmap()


def fmt(v):
    return ("%.4f" % v).rstrip("0").rstrip(".")


def advance(ch, size):
    return font["hmtx"][cmap[ord(ch)]][0] * size / float(upem)


def outline(ch, size, x, baseline):
    """The glyph as a path on the baseline at x.

    Font outlines run y-up from the baseline and SVG runs y-down from the top,
    hence the negative y scale. The letters are outlines rather than <text>
    because a favicon is read at 16 pixels, where a substituted font would not
    just look different - it would be a different mark.
    """
    pen = SVGPathPen(glyphs)
    glyphs[cmap[ord(ch)]].draw(pen)
    s = size / float(upem)
    return ('<path transform="translate(%s %s) scale(%s %s)" d="%s"/>'
            % (fmt(x), fmt(baseline), fmt(s), fmt(-s), pen.getCommands()))


ws, wv = advance("S", 135), advance("v", 112)
x0 = 128 - (ws + wv) / 2.0
paths = "\n    ".join([outline("S", 135, x0, 178),
                       outline("v", 112, x0 + ws, 180)])

svg = """<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256">
  <!-- Generated by tools/make-icons.py - do not edit by hand.
       The tab-strip favicon. favicon.ico beside it is the fallback and is the
       light-strip drawing; this file exists so a dark strip gets the inverted
       mark rather than a black disc sinking into the background. -->
  <defs>
    <linearGradient id="d" x1="0%%" y1="0%%" x2="100%%" y2="100%%">
      <stop offset="0%%" stop-color="#151515"/>
      <stop offset="100%%" stop-color="#333333"/>
    </linearGradient>
  </defs>
  <style>
    .disc { fill: url(#d); }
    .mark { fill: #ffffff; }
    @media (prefers-color-scheme: dark) {
      .disc { fill: #ffffff; }
      .mark { fill: #1a1a1a; }
    }
  </style>
  <circle class="disc" cx="128" cy="128" r="112"/>
  <g class="mark">
    %s
  </g>
</svg>
""" % paths

with open(os.path.join(ROOT, "favicon.svg"), "w", encoding="utf-8", newline="\n") as f:
    f.write(svg)
print("favicon.svg        light and dark")
